---
# Variable setup.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"
  tags: ["systemd"]

- name: Define nginx_user.
  set_fact:
    nginx_user: "{{ __nginx_user }}"
  when: nginx_user is not defined
  tags: ["systemd"]

# Setup/install tasks.
- include_tasks: "setup-{{ ansible_os_family }}.yml"
  when: not nginx_skip_install

# Modules configuration.
- import_tasks: modules.yml

- name: Check for cloudflare config
  stat:
    path: "{{ nginx_cloudflare_real_ips }}"
  register: check_cloudflare

# RTMP configuration.
- import_tasks: rtmp.yml

# Upstreams configuration
- import_tasks: upstreams.yml

# Copy vouch config if relevant
- name: Copy vouch config
  copy:
    src: files/vouch.conf
    dest: /etc/nginx/vouch.conf
    owner: root
    group: "{{ root_group }}"
    mode: 0644
  when: ports.vouch is defined

# Vhost configuration.
- import_tasks: vhosts.yml

# Sites configuration.
- import_tasks: sites.yml

# Nginx setup.
- name: Copy nginx configuration in place.
  template:
    src: "{{ nginx_conf_template }}"
    dest: "{{ nginx_conf_file_path }}"
    owner: root
    group: "{{ root_group }}"
    mode: 0644
  notify:
    - reload nginx

- name: Ensure nginx service is running as configured.
  service:
    name: nginx
    state: "{{ nginx_service_state }}"
    enabled: "{{ nginx_service_enabled }}"
