---
- name: Remove default nginx vhost config file (if configured).
  file:
    path: "{{ nginx_default_vhost_path }}"
    state: absent
  when: nginx_remove_default_vhost | bool
  notify: restart nginx

- name: Ensure nginx_vhost_path exists.
  file:
    path: "{{ nginx_vhost_path }}"
    state: directory
    mode: 0755
  notify: reload nginx

- name: Register existing copied vhosts
  ansible.builtin.find:
    file_type: file
    paths: "{{ nginx_vhost_path }}"
    patterns: "{{ nginx_provisioning_synced_patterns }}"
    excludes: "{{ nginx_provisioning_synced_excludes }}"
  register: __nginx_present
  when: nginx_provisioning_synced

- name: Register existing copied vhosts symlinks
  ansible.builtin.find:
    file_type: link
    paths: "{{ nginx_vhost_path }}"
    patterns: "{{ nginx_provisioning_synced_patterns }}"
    excludes: "{{ nginx_provisioning_synced_excludes }}"
  register: __nginx_present_link
  when: nginx_provisioning_synced

- name: Add managed vhost config files.
  template:
    src: "{{ item.template|default(nginx_vhost_template) }}"
    dest: "{{ nginx_vhost_path }}/{{ filename }}"
    force: true
    owner: root
    group: "{{ root_group }}"
    mode: 0644
  loop: "{{ nginx_vhosts | selectattr('state', 'undefined') + nginx_vhosts | selectattr('state', 'defined') | selectattr('state', 'eq', 'present') }}"
  loop_control:
    label: "{{ filename }}"
  register: __nginx_copied
  vars:
    filename: "{{ item.filename|default(item.server_name.split(' ')[0] ~ '.conf') }}"
  notify: reload nginx
  tags:
    - skip_ansible_lint

- name: Remove managed vhost config files.
  file:
    path: "{{ nginx_vhost_path }}/{{ filename }}"
    state: absent
  loop: "{{ nginx_vhosts | selectattr('state', 'defined') | selectattr('state', 'eq', 'absent') }}"
  loop_control:
    label: "{{ filename }}"
  vars:
    filename: "{{ item.filename|default(item.server_name.split(' ')[0] ~ '.conf') }}"
  notify: reload nginx
  tags:
    - skip_ansible_lint

- name: Set synchronize facts
  ansible.builtin.set_fact:
    __nginx_present_list: "{{ __nginx_present_files + __nginx_present_links }}"
    __nginx_copied_list: "{{ __nginx_copied_tmp + __nginx_copied_tmp_check }}"
  vars:
    __nginx_present_files: "{{ __nginx_present | json_query('files[*].path') | default([]) }}"
    __nginx_present_links: "{{ __nginx_present_link | json_query('files[*].path') | default([]) }}"
    __nginx_copied_tmp: "{{ __nginx_copied.results | json_query('[*].dest') | default([]) }}"
    __nginx_copied_tmp_check: "{{ __nginx_copied.results | json_query('[*].invocation.dest') | default([]) }}"
  when: nginx_provisioning_synced

- name: Remove configs not present on deployer machine (synchronize)
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
    follow: false
  loop: "{{ __nginx_present_list | difference(__nginx_copied_list) }}"
  notify: reload nginx
  when: nginx_provisioning_synced

- name: Remove legacy vhosts.conf file.
  file:
    path: "{{ nginx_vhost_path }}/vhosts.conf"
    state: absent
  notify: reload nginx
